import uuid
from datetime import datetime, timezone
from typing import Any
from sqlalchemy import (
    Column,
    DateTime,
    String,
    Boolean,
    ForeignKey,
    Text,
    JSON,
    Integer,
)
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import relationship
from backend.core.database import Base

class User(Base):
    """Database model representing a platform user/operator."""
    __tablename__ = "users"
    __allow_unmapped__ = True

    id: Any = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    name: Any = Column(String(255), nullable=False)
    email: Any = Column(String(255), nullable=False, unique=True, index=True)
    username: Any = Column(String(255), nullable=False, unique=True)
    hashed_password: Any = Column(String(255), nullable=False)
    avatar_url: Any = Column(String(500), nullable=True)
    job_title: Any = Column(String(255), nullable=True)
    department: Any = Column(String(255), nullable=True)
    timezone: Any = Column(String(100), default="UTC")
    theme: Any = Column(String(50), default="system")
    date_format: Any = Column(String(50), default="ISO")
    notification_preferences: Any = Column(JSON, nullable=True)
    created_at: Any = Column(DateTime, nullable=False, default=lambda: datetime.now(timezone.utc))
    updated_at: Any = Column(
        DateTime, 
        nullable=False, 
        default=lambda: datetime.now(timezone.utc),
        onupdate=lambda: datetime.now(timezone.utc)
    )

    # Relationships
    sessions = relationship("UserSession", back_populates="user", cascade="all, delete-orphan")
    login_history = relationship("LoginHistory", back_populates="user", cascade="all, delete-orphan")
    api_keys = relationship("ApiKey", back_populates="user", cascade="all, delete-orphan")
    llm_providers = relationship("LLMProvider", back_populates="user", cascade="all, delete-orphan")


class UserSession(Base):
    """Database model representing active user sessions."""
    __tablename__ = "user_sessions"
    __allow_unmapped__ = True

    id: Any = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    user_id: Any = Column(UUID(as_uuid=True), ForeignKey("users.id", ondelete="CASCADE"), nullable=False)
    device: Any = Column(String(255), nullable=True)
    browser: Any = Column(String(255), nullable=True)
    ip_address: Any = Column(String(100), nullable=True)
    location: Any = Column(String(255), nullable=True)
    last_active_at: Any = Column(DateTime, nullable=False, default=lambda: datetime.now(timezone.utc))
    is_active: Any = Column(Boolean, default=True, nullable=False)

    # Relationships
    user = relationship("User", back_populates="sessions")


class LoginHistory(Base):
    """Database model representing historic login attempts."""
    __tablename__ = "user_login_history"
    __allow_unmapped__ = True

    id: Any = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    user_id: Any = Column(UUID(as_uuid=True), ForeignKey("users.id", ondelete="CASCADE"), nullable=False)
    timestamp: Any = Column(DateTime, nullable=False, default=lambda: datetime.now(timezone.utc))
    ip_address: Any = Column(String(100), nullable=True)
    location: Any = Column(String(255), nullable=True)
    device: Any = Column(String(255), nullable=True)
    browser: Any = Column(String(255), nullable=True)
    success: Any = Column(Boolean, nullable=False)

    # Relationships
    user = relationship("User", back_populates="login_history")


class ApiKey(Base):
    """Database model representing platform access tokens generated by users."""
    __tablename__ = "user_api_keys"
    __allow_unmapped__ = True

    id: Any = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    user_id: Any = Column(UUID(as_uuid=True), ForeignKey("users.id", ondelete="CASCADE"), nullable=False)
    name: Any = Column(String(255), nullable=False)
    key_hash: Any = Column(String(255), nullable=False, unique=True, index=True)
    key_preview: Any = Column(String(50), nullable=False)
    permissions: Any = Column(JSON, nullable=True)
    created_at: Any = Column(DateTime, nullable=False, default=lambda: datetime.now(timezone.utc))
    last_used_at: Any = Column(DateTime, nullable=True)
    expires_at: Any = Column(DateTime, nullable=True)

    # Relationships
    user = relationship("User", back_populates="api_keys")


class IntegrationConnection(Base):
    """Database model representing credentials/endpoints for external tools."""
    __tablename__ = "integration_connections"
    __allow_unmapped__ = True

    id: Any = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    name: Any = Column(String(255), nullable=False)
    provider: Any = Column(String(100), nullable=False)  # SNOWFLAKE, BIGQUERY, POSTGRESQL, AIRFLOW, etc.
    encrypted_config: Any = Column(Text, nullable=False)  # Symmetrically encrypted JSON configs
    is_active: Any = Column(Boolean, default=True, nullable=False)
    created_at: Any = Column(DateTime, nullable=False, default=lambda: datetime.now(timezone.utc))
    updated_at: Any = Column(
        DateTime, 
        nullable=False, 
        default=lambda: datetime.now(timezone.utc),
        onupdate=lambda: datetime.now(timezone.utc)
    )


class LLMProvider(Base):
    """Database model representing custom/dynamic LLM providers configured by the user."""
    __tablename__ = "user_llm_providers"
    __allow_unmapped__ = True

    id: Any = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    user_id: Any = Column(UUID(as_uuid=True), ForeignKey("users.id", ondelete="CASCADE"), nullable=False)
    name: Any = Column(String(255), nullable=False)
    provider_type: Any = Column(String(100), nullable=False)  # OPENAI, ANTHROPIC, OLLAMA, CUSTOM
    base_url: Any = Column(String(500), nullable=False)
    model_name: Any = Column(String(255), nullable=False)
    encrypted_api_key: Any = Column(Text, nullable=True)  # Symmetrically encrypted API key
    is_active: Any = Column(Boolean, default=True, nullable=False)
    priority: Any = Column(Integer, default=0, nullable=False)
    created_at: Any = Column(DateTime, nullable=False, default=lambda: datetime.now(timezone.utc))

    # Relationships
    user = relationship("User", back_populates="llm_providers")

