"""create_bronze_tables

Revision ID: 30a632bfbea5
Revises: 5de15ab4126c
Create Date: 2026-05-19 19:56:14.174039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30a632bfbea5'
down_revision: Union[str, Sequence[str], None] = '5de15ab4126c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bronze_fda_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pipeline_run_id', sa.UUID(), nullable=False),
    sa.Column('receipt_date', sa.String(), nullable=True),
    sa.Column('serious', sa.String(), nullable=True),
    sa.Column('reporter_country', sa.String(), nullable=True),
    sa.Column('drug_name', sa.String(), nullable=True),
    sa.Column('reaction_description', sa.String(), nullable=True),
    sa.Column('seriousness_hospitalization', sa.String(), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=False),
    sa.Column('ingested_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bronze_fda_events_pipeline_run_id'), 'bronze_fda_events', ['pipeline_run_id'], unique=False)
    op.create_table('bronze_financial_candles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pipeline_run_id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('open_price', sa.Float(), nullable=True),
    sa.Column('high_price', sa.Float(), nullable=True),
    sa.Column('low_price', sa.Float(), nullable=True),
    sa.Column('close_price', sa.Float(), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('candle_timestamp', sa.DateTime(), nullable=False),
    sa.Column('ingested_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bronze_financial_candles_pipeline_run_id'), 'bronze_financial_candles', ['pipeline_run_id'], unique=False)
    op.create_index(op.f('ix_bronze_financial_candles_symbol'), 'bronze_financial_candles', ['symbol'], unique=False)
    op.create_table('bronze_github_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pipeline_run_id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('actor_login', sa.String(), nullable=True),
    sa.Column('repo_name', sa.String(), nullable=True),
    sa.Column('payload_action', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=False),
    sa.Column('ingested_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id')
    )
    op.create_index(op.f('ix_bronze_github_events_event_type'), 'bronze_github_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_bronze_github_events_pipeline_run_id'), 'bronze_github_events', ['pipeline_run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bronze_github_events_pipeline_run_id'), table_name='bronze_github_events')
    op.drop_index(op.f('ix_bronze_github_events_event_type'), table_name='bronze_github_events')
    op.drop_table('bronze_github_events')
    op.drop_index(op.f('ix_bronze_financial_candles_symbol'), table_name='bronze_financial_candles')
    op.drop_index(op.f('ix_bronze_financial_candles_pipeline_run_id'), table_name='bronze_financial_candles')
    op.drop_table('bronze_financial_candles')
    op.drop_index(op.f('ix_bronze_fda_events_pipeline_run_id'), table_name='bronze_fda_events')
    op.drop_table('bronze_fda_events')
    # ### end Alembic commands ###
