"""add_lineage_anomaly_suppression_fields

Revision ID: 68f3042fae7a
Revises: 53746b223bb7
Create Date: 2026-06-14 23:45:45.006030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68f3042fae7a'
down_revision: Union[str, Sequence[str], None] = '53746b223bb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_anomaly_baselines_table_name'), 'anomaly_baselines', ['table_name'], unique=False)
    op.add_column('anomaly_detections', sa.Column('suppressed_by_lineage', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('anomaly_detections', sa.Column('root_cause_anomaly_id', sa.UUID(), nullable=True))
    op.drop_index('ix_anomaly_detections_table_created', table_name='anomaly_detections')
    op.create_index(op.f('ix_anomaly_detections_table_name'), 'anomaly_detections', ['table_name'], unique=False)
    op.drop_index('ix_anomaly_feedback_detection_id', table_name='anomaly_feedback')
    op.create_index(op.f('ix_anomaly_feedback_anomaly_detection_id'), 'anomaly_feedback', ['anomaly_detection_id'], unique=False)
    op.create_index(op.f('ix_lineage_column_edges_source_node_id'), 'lineage_column_edges', ['source_node_id'], unique=False)
    op.create_index(op.f('ix_lineage_column_edges_target_node_id'), 'lineage_column_edges', ['target_node_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lineage_column_edges_target_node_id'), table_name='lineage_column_edges')
    op.drop_index(op.f('ix_lineage_column_edges_source_node_id'), table_name='lineage_column_edges')
    op.drop_index(op.f('ix_anomaly_feedback_anomaly_detection_id'), table_name='anomaly_feedback')
    op.create_index('ix_anomaly_feedback_detection_id', 'anomaly_feedback', ['anomaly_detection_id'], unique=False)
    op.drop_index(op.f('ix_anomaly_detections_table_name'), table_name='anomaly_detections')
    op.create_index('ix_anomaly_detections_table_created', 'anomaly_detections', ['table_name', 'created_at'], unique=False)
    op.drop_column('anomaly_detections', 'root_cause_anomaly_id')
    op.drop_column('anomaly_detections', 'suppressed_by_lineage')
    op.drop_index(op.f('ix_anomaly_baselines_table_name'), table_name='anomaly_baselines')
    # ### end Alembic commands ###

